import * as path from 'path';
import * as fs from '../core/fs';
import * as nodeFs from 'fs';
import { RUNTIME_BUNDLE_MANIFEST, RuntimeBundleManifest, ESP32_TARGET_BUILD_DIRS } from '@bscript/lang';
import { Esp32FamilyBoardName } from '../config/board-utils';
import { GLOBAL_SETTINGS } from '../config/constants';

// Linker scripts generated by the ESP-IDF build for the firmware itself. They
// describe the firmware layout and must not be used when linking user code.
const FIRMWARE_ONLY_LD_FILES = new Set(['memory.ld', 'sections.ld']);

// Extract the `-T` linker scripts and `-L` search paths of the firmware link
// command from build.ninja, and resolve the scripts to absolute paths.
export function findRomLdFiles(buildDir: string): string[] {
    const ninja = fs.readFile(path.join(buildDir, 'build.ninja'));
    const flagsLine = ninja.split('\n').find(l => l.trim().startsWith('LINK_FLAGS =') && l.includes('-T '));
    const pathLine = ninja.split('\n').find(l => l.trim().startsWith('LINK_PATH ='));
    if (!flagsLine || !pathLine) {
        throw new Error(`Cannot find the firmware link command in ${path.join(buildDir, 'build.ninja')}.`);
    }
    const ldNames = Array.from(flagsLine.matchAll(/-T\s+(\S+)/g)).map(m => m[1]).filter(n => !FIRMWARE_ONLY_LD_FILES.has(n));
    const searchDirs = Array.from(pathLine.matchAll(/-L\s*(\S+)/g)).map(m => m[1]);
    return ldNames.map(name => {
        const found = searchDirs.map(d => path.join(d, name)).find(p => fs.exists(p));
        if (!found) {
            throw new Error(`Cannot find linker script ${name} in ${searchDirs.join(', ')}.`);
        }
        return found;
    });
}

// Directory in which `board build-runtime` writes the bundle.
export function runtimeBundleOutputDir(runtimeDir: string, board: Esp32FamilyBoardName) {
    return path.join(runtimeDir, 'ports/esp32', `bundle-${board}`);
}

// Collect the build artifacts of the runtime into a self-contained bundle that
// can be used by `bscript board setup-lite` on a machine without ESP-IDF.
export function createRuntimeBundle(runtimeDir: string, board: Esp32FamilyBoardName, outDir?: string): string {
    const portDir = path.join(runtimeDir, 'ports/esp32');
    const buildDir = path.join(portDir, ESP32_TARGET_BUILD_DIRS[board]);
    const bundleDir = outDir ?? runtimeBundleOutputDir(runtimeDir, board);

    if (fs.exists(bundleDir)) {
        fs.removeDir(bundleDir);
    }
    for (const sub of ['include', 'rom-ld', 'flash', 'flash/bootloader', 'flash/partition_table']) {
        fs.makeDir(path.join(bundleDir, sub));
    }

    const copy = (from: string, to: string) => {
        if (!fs.exists(from)) {
            throw new Error(`Cannot find ${from}. Build the runtime first.`);
        }
        nodeFs.copyFileSync(from, to);
    };

    copy(path.join(buildDir, 'bluescript.elf'), path.join(bundleDir, 'bluescript.elf'));
    copy(path.join(portDir, 'std-module.bs'), path.join(bundleDir, 'std-module.bs'));
    for (const header of nodeFs.readdirSync(path.join(runtimeDir, 'core/include'))) {
        if (header.endsWith('.h')) {
            copy(path.join(runtimeDir, 'core/include', header), path.join(bundleDir, 'include', header));
        }
    }
    for (const rel of ['bluescript.bin', 'flash_args', 'bootloader/bootloader.bin', 'partition_table/partition-table.bin']) {
        copy(path.join(buildDir, rel), path.join(bundleDir, 'flash', rel));
    }
    const ldFiles = findRomLdFiles(buildDir);
    for (const ld of ldFiles) {
        copy(ld, path.join(bundleDir, 'rom-ld', path.basename(ld)));
    }

    const manifest: RuntimeBundleManifest = {
        target: board,
        vmVersion: GLOBAL_SETTINGS.VM_VERSION,
        ldFiles: ldFiles.map(f => path.basename(f)),
    };
    fs.writeFile(path.join(bundleDir, RUNTIME_BUNDLE_MANIFEST), JSON.stringify(manifest, null, 2));
    return bundleDir;
}
